Controllers/ApplicantDashboardController.cs
using BigJobbs.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BigJobbs.Controllers
{
    public class ApplicantDashboardController : Controller
    {
        IApplicantDashboardServices applicantDashboard;
        public ApplicantDashboardController(IApplicantDashboardServices applicantDashboardServices)
        {
            applicantDashboard = applicantDashboardServices;
        }

        // GET: ApplicantDashboard
        [Authorize]
        public ActionResult Index()
        {
            string applicantId = User.Identity.GetUserId();

            var ApplicantApplications = applicantDashboard.GetAllApplicantApplication(applicantId);
            return View(ApplicantApplications);
        }
    }
}

Views/Shared/_DashboardHeader.cshtml
<div class="header sticky-header">

    <!-- notification menu start -->
    <div class="menu-right">
        <div class="navbar user-panel-top">
            <div class="search-box">
                <form action="#search-results.html" method="get">
                    <input class="search-input" placeholder="Search Here..." type="search" id="search">
                    <button class="search-submit" value=""><span class="fa fa-search"></span></button>
                </form>
            </div>
            <div class="user-dropdown-details d-flex">
                <div class="profile_details_left">
                    <ul class="nofitications-dropdown">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-bell-o"></i><span class="badge blue">3</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="notification_header">
                                        <h3>You have 3 new notifications</h3>
                                    </div>
                                </li>
                                <li>
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar1.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>Johnson purchased template</p>
                                            <span>Just Now</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="odd">
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar2.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>New customer registered </p>
                                            <span>1 hour ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar3.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>Lorem ipsum dolor sit amet </p>
                                            <span>2 hours ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <div class="notification_bottom">
                                        <a href="#all" class="bg-primary">See all notifications</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-comment-o"></i><span class="badge blue">4</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="notification_header">
                                        <h3>You have 4 new messages</h3>
                                    </div>
                                </li>
                                <li>
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar1.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>Johnson purchased template</p>
                                            <span>Just Now</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="odd">
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar2.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>New customer registered </p>
                                            <span>1 hour ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar3.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>Lorem ipsum dolor sit amet </p>
                                            <span>2 hours ago</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="grid">
                                        <div class="user_img"><img src="assets/images/avatar1.jpg" alt=""></div>
                                        <div class="notification_desc">
                                            <p>Johnson purchased template</p>
                                            <span>Just Now</span>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <div class="notification_bottom">
                                        <a href="#all" class="bg-primary">See all messages</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="profile_details">
                    <ul>
                        <li class="dropdown profile_details_drop">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdownMenu3" aria-haspopup="true"
                               aria-expanded="false">
                                <div class="profile_img">
                                    <img src="assets/images/profileimg.jpg" class="rounded-circle" alt="" />
                                    <div class="user-active">
                                        <span></span>
                                    </div>
                                </div>
                            </a>
                            <ul class="dropdown-menu drp-mnu" aria-labelledby="dropdownMenu3">
                                <li class="user-info">
                                    <h5 class="user-name">John Deo</h5>
                                    <span class="status ml-2">Available</span>
                                </li>
                                <li> <a href="#"><i class="lnr lnr-user"></i>My Profile</a> </li>
                                <li> <a href="#"><i class="lnr lnr-users"></i>1k Followers</a> </li>
                                <li> <a href="#"><i class="lnr lnr-cog"></i>Setting</a> </li>
                                <li> <a href="#"><i class="lnr lnr-heart"></i>100 Likes</a> </li>
                                <li class="logout"> <a href="#sign-up.html"><i class="fa fa-power-off"></i> Logout</a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--notification menu end -->
</div>

Views/Shared/_Footer.cshtml
    <!-- Footer Start-->
    <div class="footer-area footer-bg footer-padding">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                    <div class="single-footer-caption mb-50">
                        <div class="single-footer-caption mb-30">
                            <div class="footer-tittle">
                                <h4>About Us</h4>
                                <div class="footer-pera">
                                    <p>Heaven frucvitful doesn't cover lesser dvsays appear creeping seasons so behold.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Contact Info</h4>
                            <ul>
                                <li>
                                    <p>
                                        Address: California, USA.
                                    </p>
                                </li>
                                <li><a href="#">Phone : +8880 44338899</a></li>
                                <li><a href="#">Email : selfmadecode.com</a></li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Important Link</h4>
                            <ul>
                                <li><a href="#"> View Project</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Testimonial</a></li>
                                <li><a href="#">Proparties</a></li>
                                <li><a href="#">Support</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Newsletter</h4>
                            <div class="footer-pera footer-pera2">
                                <p>Heaven fruitful doesn't over lesser in days. Appear creeping.</p>
                            </div>
                            <!-- Form -->
                            @*<div class="footer-form">
                                <div id="mc_embed_signup">
                                    <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                          method="get" class="subscribe_form relative mail_part">
                                        <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                               class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = ' Email Address '">
                                        <div class="form-icon">
                                            <button type="submit" name="submit" id="newsletter-submit"
                                                    class="email_icon newsletter-submit button-contactForm">
                                                <img src="assets/img/icon/form.png" alt="">
                                            </button>
                                        </div>
                                        <div class="mt-10 info"></div>
                                    </form>
                                </div>
                            </div>*@
                        </div>
                    </div>
                </div>
            </div>
            <!--  -->
            
        </div>
    </div>
    <!-- footer-bottom area -->
    <div class="footer-bottom-area footer-bg">
        <div class="container">
            <div class="footer-border">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-xl-10 col-lg-10 ">
                        <div class="footer-copy-right">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy; SelfMade 2020
                            </p>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2">
                        <div class="footer-social f-right">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fas fa-globe"></i></a>
                            <a href="#"><i class="fab fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*template start*@
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/assets/css/price_rangs.css">
    <link rel="stylesheet" href="~/Content/assets/css/slicknav.css">
    <link rel="stylesheet" href="~/Content/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/assets/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/assets/css/slick.css">
    <link rel="stylesheet" href="~/Content/assets/css/nice-select.css">
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
    @*end*@


</head>
<body>

    @Html.Partial("_NavBar")
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*start*@

    <!-- JS here -->
    <!-- All JS Custom Plugins Link Here here -->
    <script src="~/Content/assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="~/Content/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/Content/assets/js/popper.min.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/Content/assets/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/Content/assets/js/owl.carousel.min.js"></script>
    <script src="~/Content/assets/js/slick.min.js"></script>
    <script src="~/Content/assets/js/price_rangs.js"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="~/Content/assets/js/wow.min.js"></script>
    <script src="~/Content/assets/js/animated.headline.js"></script>
    <script src="~/Content/assets/js/jquery.magnific-popup.js"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="~/Content/assets/js/jquery.scrollUp.min.js"></script>
    <script src="~/Content/assets/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/assets/js/jquery.sticky.js"></script>

    <!-- contact js -->
    <script src="~/Content/assets/js/contact.js"></script>
    <script src="~/Content/assets/js/jquery.form.js"></script>
    <script src="~/Content/assets/js/jquery.validate.min.js"></script>
    <script src="~/Content/assets/js/mail-script.js"></script>
    <script src="~/Content/assets/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="~/Content/assets/js/plugins.js"></script>
    <script src="~/Content/assets/js/main.js"></script>

    @*end*@
</body>
</html>

Views/Shared/_NavBar.cshtml
@using Microsoft.AspNet.Identity

<header>
    <!-- Header Start -->
    <div class="header-area header-transparrent">
        <div class="headder-top header-sticky">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-2">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="index.html"><img src=~/Content/assets/img/logo/logo.png alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9">
                        <div class="menu-wrapper">
                            <!-- Main-menu -->
                            <div class="main-menu">
                                <nav class="d-none d-lg-block   ">
                                    <ul id="navigation">
                                        @{
                                            if (User.IsInRole(BigJobbs.Models.Roles.admin))
                                            {
                                                <li>@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>

                                            }
                                            else
                                            {
                                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                                <li><a href="@Url.Action("AllJobs","Home", new {id = 0 })">Find a Jobs </a></li>
                                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                                @*<li><a href="about.html">About</a></li>*@
                                                if (Request.IsAuthenticated)
                                                {
                                                    <li>@Html.ActionLink("Dashboard", "Index", "ApplicantDashboard")</li>
                                                }
                                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                            }
                                        }
                                        <li>
                                            @Html.Partial("_LoginPartial")
                                        </li>

                                    </ul>

                                </nav>
                            </div>
                            <!-- Header-btn -->
                            @*<div class="header-btn d-none f-right d-lg-block">

                                    <a href="#" class="btn head-btn1">Register</a>

                                    <a href="#" class="btn head-btn2">Login</a>

                                </div>*@
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>

Views/Shared/_SideBar.cshtml
<!-- sidebar menu start -->
<div class="sidebar-menu sticky-sidebar-menu">

    <!-- logo start -->
    <div class="logo">
        <h1>BiggJobb</h1>
    </div>

    <!-- if logo is image enable this -->
    <!-- image logo --
    <div class="logo">
      <a href="index.html">
        <img src="image-path" alt="Your logo" title="Your logo" class="img-fluid" style="height:35px;" />
      </a>
    </div>
    <!-- //image logo -->

    <div class="logo-icon text-center" style="background-color: transparent">
        <a href="" title="logo"><img src="~/Content/assets/img/logo/logo.png"> </a>
    </div>
    <!-- //logo end -->

    <div class="sidebar-menu-inner">

        <!-- sidebar nav start -->
        <ul class="nav nav-pills nav-stacked custom-nav">
            <li class="active">
                <a href="@Url.Action("Index", "Dashboard")"><i class="fas fa-user"></i><span> Dashboard</span></a>
            </li>
            <li class="menu-list">
                <a href="#">
                    <i class="fa fa-cogs"></i>
                    <span>Applications <i class="lnr lnr-chevron-right"></i></span>
                </a>
                <ul class="sub-menu-list">
                    <li><a href="@Url.Action("GetPendingApplications", "Dashboard")">Pending</a> </li>
                    <li><a href="@Url.Action("GetAcceptedApplications", "Dashboard")">Accepted</a> </li>
                    <li><a href="@Url.Action("GetRejectedApplications", "Dashboard")">Rejected</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("GetAllApplicants", "Dashboard")"><i class="fa fa-table"></i> <span>Applicants</span></a></li>
            <li><a href="@Url.Action("GetAllJobs", "Dashboard")"><i class="fa fa-th"></i> <span>All Jobs</span></a></li>
            <li><a href="@Url.Action("AddJob", "Dashboard")"><i class="fa fa-file-text"></i> <span>Add Jobs</span></a></li>
        </ul>
        <!-- //sidebar nav end -->
        <!-- toggle button start -->
        <a class="toggle-btn">
            <i class="fa fa-angle-double-left menu-collapsed__left"><span>Collapse Sidebar</span></i>
            <i class="fa fa-angle-double-right menu-collapsed__right"></i>
        </a>
        <!-- //toggle button end -->
    </div>
</div>
<!-- //sidebar menu end -->