Controllers/ApplicantDashboardController.cs
using BigJobbs.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BigJobbs.Controllers
{
    public class ApplicantDashboardController : Controller
    {
        IApplicantDashboardServices applicantDashboard;
        public ApplicantDashboardController(IApplicantDashboardServices applicantDashboardServices)
        {
            applicantDashboard = applicantDashboardServices;
        }

        // GET: ApplicantDashboard
        [Authorize]
        public ActionResult Index()
        {
            string applicantId = User.Identity.GetUserId();

            var ApplicantApplications = applicantDashboard.GetAllApplicantApplication(applicantId);
            return View(ApplicantApplications);
        }
    }
}

Controllers/DashboardController.cs
using BigJobbs.Infrastructure.ViewModels;
using BigJobbs.Interfaces;
using BigJobbs.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BigJobbs.Controllers
{
    // to avoid break in code when the role isn't spelt correctly
    [Authorize(Roles = BigJobbs.Models.Roles.admin)]
    public class DashboardController : Controller
    {
        IAdminDashboardServices adminDS;
        IFile fileExtension;

        public DashboardController(IAdminDashboardServices iAdS, IFile _file)
        {
            adminDS = iAdS;
            fileExtension = _file;
        }

        // GET: Dashboard
        public ActionResult Index()
        {
            var NumberOfJobs = adminDS.NumberOfApplication();

            return View(NumberOfJobs);
        }


        [HttpGet]
        public ActionResult AddJob()
        {
            var jobCategories = adminDS.GetAllJobCategories();
            var jobTypes = adminDS.GetAllJobTypes();

            var vm = new JobViewModel
            {
                jobCategory = jobCategories,
                jobType = jobTypes,
                job = new Job()
            };
            
            return View("JobForm", vm);
        }


        [HttpPost]
        public ActionResult SaveJob(JobViewModel newJob)
        {

            string imageExtenstion = Path.GetExtension(newJob.job.ImageFile.FileName);

            var isJpeg = fileExtension.IsJpegOrPng(imageExtenstion);

            if (!ModelState.IsValid || isJpeg == false)
            {
                var job = new JobViewModel
                {
                    job = newJob.job,
                    jobCategory = adminDS.GetAllJobCategories(),
                    jobType = adminDS.GetAllJobTypes()

                };


                if (isJpeg == false)
                    ViewBag.ImageError = "Only .jpeg, .png or .jpg files allowed";


                return View("JobForm", job);
            }  

            if (newJob.job.Id == 0)
            {
                adminDS.SaveJob(newJob.job);

                return RedirectToAction("Index");
            }
            else
            {
                adminDS.UpdateJobInDb(newJob.job);

                return RedirectToAction("Index");
            }
        }


        public ActionResult GetAllJobs()
        {
            var jobs = adminDS.GetAllJobs();

            return View(jobs);
        }


        public ActionResult EditJob(int id)
        {
            var jobInDb = adminDS.EditJob(id);


            if (jobInDb == null)
                return HttpNotFound("No job matched the Id");


            return View("JobForm", jobInDb);
        }


        public ActionResult GetAllApplicants()
        {
            var allApplicants = adminDS.GetAllApplicants();

            return View("AllApplicants", allApplicants);
        }


        public ActionResult GetPendingApplications()
        {
            var pendingApplications = adminDS.GetApplications(JobApplicationStatus.pending);
            
            ViewBag.ApplicationStatus = "Pending";
            return View("PendingApplications", pendingApplications);
        }


        public ActionResult GetRejectedApplications()
        {
            var rejectedApplications = adminDS.GetApplications(JobApplicationStatus.rejected);

            ViewBag.ApplicationStatus = "Rejected";
            return View("ProcessedApplications", rejectedApplications);
        }


        public ActionResult GetAcceptedApplications()
        {
            var acceptedApplications = adminDS.GetApplications(JobApplicationStatus.accepted);

            ViewBag.ApplicationStatus = "Accepted";
            return View("ProcessedApplications", acceptedApplications);
        }


        public ActionResult ApplicationDetails(int applicantId, int jobId)
        {
            var application = adminDS.GetJobAndApplicantDetails(applicantId, jobId);

            if (application == null)
                return HttpNotFound("No application matching the Id");

            return View(application);
        }


        public ActionResult AcceptApplication(int applicantId, int jobId)
        {
            var alreadyProcessed = adminDS.ProcessApplication(applicantId, jobId, JobApplicationStatus.accepted);

            if (alreadyProcessed == true)
                return HttpNotFound("Application Already processed! or does not exist");

            return RedirectToAction("GetPendingApplications");
        }


        public ActionResult RejectApplication(int applicantId, int jobId)
        {
            var alreadyProcessed = adminDS.ProcessApplication(applicantId, jobId, JobApplicationStatus.rejected);

            if (alreadyProcessed == true)
                return HttpNotFound("Application Already processed!");

            return RedirectToAction("GetPendingApplications");
        }
    }
}

Controllers/JobController.cs
using BigJobbs.Infrastructure.ViewModels;
using BigJobbs.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BigJobbs.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        IJobServices JobService;
        IFile fileExtension;


        public JobController(IJobServices jobService, IFile _file)
        {
            JobService = jobService;
            fileExtension = _file;
        }


        // GET: Job
        public ActionResult Index()
        {
            return View();
        }


        [AllowAnonymous]
        public ActionResult JobDetails(int id)
        {
            var currentUserId = User.Identity.GetUserId();

            if (string.IsNullOrEmpty(currentUserId))
            {
                var jobDetails = JobService.GetOnlyJobDetails(id);

                if (jobDetails.Job == null)
                    return HttpNotFound("No Available job matching the Id");

                return View(jobDetails);
            }
            else
            {
                var jobAndApplicantDetails = JobService.GetJobAndApplicantDetails(id, currentUserId);

                if (jobAndApplicantDetails.Job == null)
                    return HttpNotFound("No Available job matching the Id");

                return View(jobAndApplicantDetails);
            }
        }



        public ActionResult ApplyForJob(int jobId)
        {
            var currentUserId = User.Identity.GetUserId();

            var jobDetails = JobService.ApplyForJob(jobId, currentUserId);

            if (jobDetails == null)
                return HttpNotFound("No Available job matching the Id");

            return View(jobDetails);
        }


        public ActionResult EditApplication(int jobId)
        {
            var currentUserId = User.Identity.GetUserId();

            var jobDetails = JobService.EditApplication(jobId, currentUserId);

            if (jobDetails == null)
                return HttpNotFound("Sorry, you have not applied for this Job!");

            return View("ApplyForJob", jobDetails);
        }



        [HttpPost]
        public ActionResult SaveApplication(UserAndJobViewModel userAndJobViewModel)
        {
            var currentUserId = User.Identity.GetUserId();

            string passportExtension = Path.GetExtension(userAndJobViewModel.Applicant.PassportFile.FileName);
            string pdfExtension = Path.GetExtension(userAndJobViewModel.Applicant.PdfFile.FileName);

            //Validate applicant passport...returns the view if the passport file is not in the correct format
            var isJpeg = fileExtension.IsJpegOrPng(passportExtension);


            if(isJpeg == false)
            {
                ViewBag.PassportError = "Only .jpeg, .png or .jpg files allowed";

                return View("ApplyForJob", userAndJobViewModel);
            }


            var isPdf = fileExtension.IsPdf(pdfExtension);

            //Validate applicant pdf...returns the view if the pdf file is not in the correct format
            if(isPdf == false)
            {
                ViewBag.PdfError = "Only .pdf files allowed";

                return View("ApplyForJob", userAndJobViewModel);
            }


            // if the model is not in the right format
            if (!ModelState.IsValid)
            {
                var userAndJob = new UserAndJobViewModel
                {
                    Applicant = userAndJobViewModel.Applicant,
                    Job = userAndJobViewModel.Job
                };

                return View("ApplyForJob", userAndJob);
            }


            try
            {
                if(userAndJobViewModel.Applicant.Id == 0)
                {
                    var applicationAlreadyProcessed = JobService.SaveApplication(userAndJobViewModel);

                    if (applicationAlreadyProcessed == true)
                    {
                        return HttpNotFound("Application Already processed!");
                    }
                }
                else
                {
                    var applicationAlreadyProcessed = JobService.UpdateApplication(userAndJobViewModel, currentUserId);
                    
                    if(applicationAlreadyProcessed == true)
                    {
                        return HttpNotFound("Application Already processed!");
                    }
                }
            }
            catch (Exception ex)
            {
                ex.Message.ToString();
            }
            return View("ApplicationStatus", userAndJobViewModel);
        }
    }
}

Views/ApplicantDashboard/Index.cshtml
@model IEnumerable<BigJobbs.Models.Applicant>
@using Microsoft.AspNet.Identity

<style>
    table{

        font-size: 17px;
        width: 100%;
    }
    .card{
        margin-top: 50px;
    }
    td{
        padding-left: 100px;
    }
    .btngreen{
        background-color: green;
    }
    .btnblue {
        background-color: rgba(10, 3, 73, 0.842);
    }
    .trrr{
        background-color: rgba(10, 3, 73, 0.842);
    }
</style>

<div class="container">
    <h1 style="margin-top: 50px;">Welcome back <span style="color: deeppink">@User.Identity.GetUserName()!</span></h1>
    <div class="card" style="margin-top: 10px">
        <div class="card-body">
            <h3 class="card-title" style="margin-bottom: 30px;">Here is a list of all your applications</h3>

            @if (!Model.Any())
            {
                <h3 class="btn btnblue">You've not applied for any job</h3>
            }
            else
            {
                <table id="items" class="table table-hover table-striped table-responsive text-center">
                    <tr style="background-color: rgba(10, 3, 73, 0.842); color: white" class="btnblue col-12">
                        <th style="width: 15%">Job Name</th>
                        <th style="width: 15%">Hiring Company</th>
                        <th style="width: 15%">Salary</th>
                        <th>Job Type</th>
                        <th>App. Status</th>
                        <th></th>
                        <th></th>
                    </tr>
                    @foreach (var application in Model)
                    {
                        <tr class="info">
                            @*<td>@Html.ActionLink(application.Job.Name, "EditJob", "Dashboard", new { id = application.Job.Name }, null)</td>*@
                            <td>@application.Job.Name</td>
                            <td>@application.Job.HiringCompany</td>
                            <td>@application.Job.Salary</td>
                            <td>@application.Job.JobType.Name </td>
                            <td>@application.JobApplicationStatus </td>
                            @{
                                if (application.JobApplicationStatus == BigJobbs.Models.JobApplicationStatus.pending)
                                {
                                    <td>
                                        @Html.ActionLink("Edit Application", "EditApplication", "Job", new { jobId = application.Job.Id },
                                         new { @class = "btn btnblue" })
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        Your application have has processed!
                                    </td>
                                }
                            }
                            <td>
                                @Html.ActionLink("Job Details", "JobDetails", "Job", new { id = application.Job.Id },
                                     new { @class = "btn btngreen" })
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>

    </div>
</div>